"""add tag option weight and paper rating

Revision ID: c379c1f66660
Revises: 9da82b35fdaf
Create Date: 2026-08-12 07:59:01.045567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c379c1f66660'
down_revision: Union[str, Sequence[str], None] = '9da82b35fdaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('paper', sa.Column('rating', sa.Integer(), nullable=True))
    # server_default backfills existing rows (this table already has data in
    # production) with 0; dropped right after so future inserts rely on the
    # ORM-side default instead of a column default living in the schema.
    op.add_column('tagoption', sa.Column('weight', sa.Float(), nullable=False, server_default='0'))
    with op.batch_alter_table('tagoption') as batch_op:
        batch_op.alter_column('weight', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tagoption', 'weight')
    op.drop_column('paper', 'rating')
    # ### end Alembic commands ###
